# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsEmployee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_state', models.CharField(blank=True, max_length=2, null=True)),
                ('license_expiration', models.DateField(blank=True, null=True)),
                ('medical_certificate_expiration', models.DateField(blank=True, null=True)),
                ('last_mvr', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cs_employee',
            },
        ),
        migrations.CreateModel(
            name='CsEntityEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventdetails', to='champschedule.CsEmployee')),
            ],
            options={
                'db_table': 'cs_entity_events',
            },
        ),
        migrations.CreateModel(
            name='CsEntitytype',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'cs_entitytype',
            },
        ),
        migrations.CreateModel(
            name='CsEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('entitytype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsEntitytype')),
            ],
            options={
                'db_table': 'cs_equipment',
            },
        ),
        migrations.CreateModel(
            name='CsEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cs_event',
            },
        ),
        migrations.CreateModel(
            name='CsGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cs_group',
            },
        ),
        migrations.CreateModel(
            name='CsHotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('entitytype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsEntitytype')),
            ],
            options={
                'db_table': 'cs_hotel',
            },
        ),
        migrations.CreateModel(
            name='CsLocation',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'cs_location',
            },
        ),
        migrations.CreateModel(
            name='CsRentalcar',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('entitytype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsEntitytype')),
            ],
            options={
                'db_table': 'cs_rentalcar',
            },
        ),
        migrations.CreateModel(
            name='CsSubgroup',
            fields=[
                ('subgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('subgroup_name', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsGroup')),
            ],
            options={
                'db_table': 'cs_subgroup',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_state', models.CharField(blank=True, max_length=2, null=True)),
                ('license_expiration', models.DateField(blank=True, null=True)),
                ('medical_certificate_expiration', models.DateField(blank=True, null=True)),
                ('last_mvr', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('license_image', models.CharField(blank=True, max_length=100, null=True)),
                ('compressed_license_image', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_group', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_group', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='champschedule.Driver')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Eventdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('employee', models.ManyToManyField(to='champschedule.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='csevent',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsLocation'),
        ),
        migrations.AddField(
            model_name='csentityevents',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsEquipment'),
        ),
        migrations.AddField(
            model_name='csentityevents',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeedetails', to='champschedule.CsEvent'),
        ),
        migrations.AddField(
            model_name='csentityevents',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsHotel'),
        ),
        migrations.AddField(
            model_name='csentityevents',
            name='rentalcar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsRentalcar'),
        ),
        migrations.AddField(
            model_name='csemployee',
            name='entitytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsEntitytype'),
        ),
        migrations.AddField(
            model_name='csemployee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='champschedule.CsGroup'),
        ),
        migrations.AddField(
            model_name='csemployee',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.CsSubgroup'),
        ),
    ]
