# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsdriver',
            name='driver_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
