# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0002_wmsdriver_driver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsdriver',
            name='sub_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
