# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0002_auto_20170728_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetail',
            old_name='event_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='eventdetail',
            old_name='event_start',
            new_name='start',
        ),
    ]
