# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0003_wmsdriver_sub_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_state', models.CharField(blank=True, max_length=2, null=True)),
                ('license_expiration', models.DateField(blank=True, null=True)),
                ('medical_certificate_expiration', models.DateField(blank=True, null=True)),
                ('last_mvr', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('license_image', models.CharField(blank=True, max_length=100, null=True)),
                ('compressed_license_image', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_group', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_group', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
