# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0003_auto_20170801_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='license_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
