# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0004_driver_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
