# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0004_auto_20170803_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ManyToManyField(to='champschedule.Location'),
        ),
    ]
