# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0006_remove_csevent_all_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='location',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.Location'),
        ),
    ]
