# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0007_auto_20170524_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
