# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0007_auto_20170810_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
