# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0008_auto_20170815_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='employee',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.Employee'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='champschedule.Event'),
        ),
    ]
