# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0009_auto_20170719_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authgrouppermissions',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='authgrouppermissions',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authgrouppermissions',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='authusergroups',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='authusergroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authusergroups',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
    ]
