# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0010_auto_20170822_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
