# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0011_series_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdiemrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_month', models.CharField(max_length=30)),
            ],
        ),
    ]
