# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0012_perdiemrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdiem',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('days_jantomar', models.IntegerField(blank=True, null=True)),
                ('jantomar', models.IntegerField(blank=True, null=True)),
                ('days_martoapr', models.IntegerField(blank=True, null=True)),
                ('martoapr', models.IntegerField(blank=True, null=True)),
                ('days_aprtomay', models.IntegerField(blank=True, null=True)),
                ('aprtomay', models.IntegerField(blank=True, null=True)),
                ('days_maytojun', models.IntegerField(blank=True, null=True)),
                ('maytojun', models.IntegerField(blank=True, null=True)),
                ('days_juntojul', models.IntegerField(blank=True, null=True)),
                ('juntojul', models.IntegerField(blank=True, null=True)),
                ('days_jultoaug', models.IntegerField(blank=True, null=True)),
                ('jultoaug', models.IntegerField(blank=True, null=True)),
                ('days_augtosep', models.IntegerField(blank=True, null=True)),
                ('augtosep', models.IntegerField(blank=True, null=True)),
                ('days_septooct', models.IntegerField(blank=True, null=True)),
                ('septooct', models.IntegerField(blank=True, null=True)),
                ('days_octtonov', models.IntegerField(blank=True, null=True)),
                ('octtonov', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'champschedule_perdiem',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='location_color',
            field=models.CharField(default='#3a87ad', max_length=7),
        ),
    ]
