# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champschedule', '0013_auto_20170830_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csemployee',
            name='entitytype',
        ),
        migrations.RemoveField(
            model_name='csemployee',
            name='group',
        ),
        migrations.RemoveField(
            model_name='csemployee',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='csentityevents',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='csentityevents',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='csentityevents',
            name='event',
        ),
        migrations.RemoveField(
            model_name='csentityevents',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='csentityevents',
            name='rentalcar',
        ),
        migrations.RemoveField(
            model_name='csequipment',
            name='entitytype',
        ),
        migrations.RemoveField(
            model_name='csevent',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='cshotel',
            name='entitytype',
        ),
        migrations.RemoveField(
            model_name='csrentalcar',
            name='entitytype',
        ),
        migrations.RemoveField(
            model_name='cssubgroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='CsEmployee',
        ),
        migrations.DeleteModel(
            name='CsEntityEvents',
        ),
        migrations.DeleteModel(
            name='CsEntitytype',
        ),
        migrations.DeleteModel(
            name='CsEquipment',
        ),
        migrations.DeleteModel(
            name='CsEvent',
        ),
        migrations.DeleteModel(
            name='CsGroup',
        ),
        migrations.DeleteModel(
            name='CsHotel',
        ),
        migrations.DeleteModel(
            name='CsLocation',
        ),
        migrations.DeleteModel(
            name='CsRentalcar',
        ),
        migrations.DeleteModel(
            name='CsSubgroup',
        ),
    ]
